<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>InkMARC.Clean.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\eng.traineddata" />
    <None Remove="Resources\Images\Q.png" />
    <None Remove="Resources\Images\Qa.png" />
    <None Remove="Resources\Images\Qb.png" />
    <None Remove="Resources\Images\QF.png" />
    <None Remove="Resources\Images\QF2.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="InkMARC.Clean.ico" />
    <Content Include="Resources\Images\Q.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Qa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Qb.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\QF.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\QF2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HDF.PInvoke.NETStandard" Version="1.10.502" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.23.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.23.2" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <PackageReference Include="WindowsAPICodePack" Version="8.0.12" />
  </ItemGroup>

</Project>
